queue:
  name: Hosted Ubuntu 1604
  timeoutInMinutes: 6000

trigger:
  batch: true
  branches:
    include:
    - master

variables:
  python.version: '3.7'

steps:

- task: UsePythonVersion@0
  displayName: 'Use Python $(python.version)'
  inputs:
    versionSpec: '$(python.version)'

- script: 'pip install --upgrade pip'
  displayName: 'Upgrade pip'

- script: 'pip install setuptools wheel twine'
  displayName: 'Install dependencies'

- script: "git tag $(date +'v%Y.%m.%d.%H.%M.%S')"
  displayName: 'Create datetime version tag'

- script: 'python setup.py bdist bdist_wheel && twine upload --repository-url https://test.pypi.org/legacy/ -u $(pypi_username) -p $(pypi_password) dist/*'
  displayName: PYPI deploy
