queue:
  name: Hosted Ubuntu 1604
  timeoutInMinutes: 10

trigger:
  batch: true
  branches:
    include:
    - master

variables:
  python.version: '3.7'

steps:

- task: UsePythonVersion@0
  displayName: 'Use Python $(python.version)'
  inputs:
    versionSpec: '$(python.version)'

- script: 'pip install --upgrade pip'
  displayName: 'Upgrade pip'

- script: 'pip install flake8 && pip install . && flake8 .'
  displayName: Flake8